### ISSUE TITLE
Result return 

### ISSUE THREAD

**Issue by waghanza** [ray-ang/basicphp#1]
Hi @ray-ang,

On this line, I can see that declaring a `route_class` only `return`
https://github.com/ray-ang/basicphp/blob/3a06f073c165a9b002b4141f0485a394b68036c5/functions.php#L120

does it not need to **render** something (`echo`, `print` or else) ?

Regards,

**Comment by ray-ang** [comment]
Hi @waghanza. It returns a method of the class. In the method of the class controller, there you can echo json data, for API use, or use the view( ) function to render a view.

**Comment by waghanza** [comment]
@ray-ang I see ... It differs much than other frameworks implementations then

**Comment by ray-ang** [comment]
@waghanza. The routing mechanism is the same as with other frameworks, like Laravel's routing below.

Route::get('/user', 'UserController@index');

The main difference is BasicPHP is not Composer-dependent, but it can be installed alongside if needed. The routing of most PHP frameworks as designed for REST environments. BasicPHP also supports REST, but it is JSON-RPC-first, then REST-RPC, then REST. Other frameworks get their functionalities from methods inside classes from other packages. BasicPHP has the functions in functions.php for functionality.

**Comment by waghanza** [comment]
@ray-ang Yeah, I see totaly up with that. A big difference is also that the code is **NOT** managed externally. I mean it's raw `php` not a external tool / repo
